apiVersion: v1
kind: ConfigMap
metadata:
  name: microservicios-configmap
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_CONFIG_IMPORT: configserver:http://config-server-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8070/eureka/

