apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata: 
      labels:
        app: config-server
    spec: 
      containers:
        - name: config-server
          image: jhonattan25/app-microservicios-config-server:1.0.0
          ports:
          - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
